[package]
name = "admin"
version = "0.1.0"
edition = "2021"

[dependencies]
base.path = "../base"
shared = { path = "../shared", features = ["permission"] }

anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel-async.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
unic-langid.workspace = true
