package yelken:plugin@0.1.0;

interface init {
  record host-info {
    version: string,
  }

  record impl {
    namespace: string,
    name: string,
    version: string,
    iface: string,
  }

  record plugin-info {
    id: string,
    version: string,
    impls: list<impl>,
  }

  register: func(host: host-info) -> plugin-info;
}

world root {
  export init;
}
