[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
base.path = "../../base"

anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel-async.workspace = true
log.workspace = true
serde.workspace = true
