services:
  postgres:
    image: postgres:17
    restart: always
    environment: 
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: yelken
      POSTGRES_DB: yelken
    volumes: 
      - ./init:/docker-entrypoint-initdb.d:ro,z
    networks:
      - app-network
  yelken:
    image: bwqr/yelken:0.1.0-alpha2
    restart: always
    environment:
      RUST_LOG: info
      YELKEN_ENV: dev
      YELKEN_BIND_ADDRESS: 0.0.0.0:8080
      YELKEN_DATABASE_URL: postgres://yelken:toor@postgres/yelken
      YELKEN_SECRET_KEY: super_secret_key
      YELKEN_SITE_URL: http://127.0.0.1:8080
      YELKEN_APP_URL: http://127.0.0.1:8080
      YELKEN_APP_ASSETS_DIR: /app/dist
      YELKEN_RELOAD_TEMPLATES: yes
      YELKEN_STORAGE_DIR: /storage
      YELKEN_TMP_DIR: /tmp
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - ./theme:/storage/themes/default:z
    depends_on:
      - postgres
networks: 
  app-network:
    driver: bridge
