package yelken:handler@0.1.0;

interface init {
  enum hook {
    pre-load,
    loading,
    loaded,
    post-load,
  }

  record reg {
    path: string,
    hook: hook,
  }

  register: func() -> list<reg>;
}

interface page {
  record request {
    url: string,
  }

  record page {
    head: string,
    body: string,
    scripts: string,
  }

  pre-load: func(req: request);
  loading: func(req: request, page: page) -> page;
  loaded: func(page: page) -> page;
  post-load: func(req: request);

  render: func(id: string, opts: list<string>) -> string;
}

world root {
  export init;
  export page;
}
