[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
base.path = "../base"

axum.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-http = { workspace = true, features = ["fs"] }
