[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
base.path = "../base"

axum.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tower.workspace = true

include_dir = "0.7.4"
mime_guess = "2.0.5"
